### ISSUE TITLE
配置agent后启动报错

### ISSUE THREAD

**Issue by LeeXinjian** [alwans/code-diff#6]
启动参数：

javaagent:./lib/jacocoagent.jar=output=tcpserver,port=8000,address=*,branchName=jacocoTest,commitId=5a57b64e4af618ca571b3d0bf8fa20965e585919"

报错信息：
Connected to the target VM, address: '127.0.0.1:64517', transport: 'socket'
Failed to instantiate SLF4J LoggerFactory
Reported exception:
java.lang.NoClassDefFoundError: org/jacoco/agent/rt/internal_baf4693/core/runtime/ChainNodeHandle
	at sun.util.resources.zh.CalendarData_zh.getContents(CalendarData_zh.java)
	at sun.util.resources.OpenListResourceBundle.loadLookup(OpenListResourceBundle.java:137)
	at sun.util.resources.OpenListResourceBundle.loadLookupTablesIfNecessary(OpenListResourceBundle.java:128)
	at sun.util.resources.OpenListResourceBundle.handleKeySet(OpenListResourceBundle.java:96)
	at java.util.ResourceBundle.containsKey(ResourceBundle.java:1824)
	at sun.util.locale.provider.LocaleResources.getCalendarData(LocaleResources.java:129)
	at sun.util.locale.provider.CalendarDataProviderImpl.getFirstDayOfWeek(CalendarDataProviderImpl.java:50)
	at sun.util.locale.provider.CalendarDataUtility$CalendarWeekParameterGetter.getObject(CalendarDataUtility.java:197)
	at sun.util.locale.provider.CalendarDataUtility$CalendarWeekParameterGetter.getObject(CalendarDataUtility.java:182)
	at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObjectImpl(LocaleServiceProviderPool.java:281)
	at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObject(LocaleServiceProviderPool.java:265)
	at sun.util.locale.provider.CalendarDataUtility.retrieveFirstDayOfWeek(CalendarDataUtility.java:52)
	at java.util.Calendar.setWeekCountData(Calendar.java:3379)
	at java.util.Calendar.<init>(Calendar.java:1600)
	at java.util.GregorianCalendar.<init>(GregorianCalendar.java:737)
	at java.util.Calendar$Builder.build(Calendar.java:1482)
	at sun.util.locale.provider.CalendarProviderImpl.getInstance(CalendarProviderImpl.java:88)
	at java.util.Calendar.createCalendar(Calendar.java:1666)
	at java.util.Calendar.getInstance(Calendar.java:1655)
	at java.text.SimpleDateFormat.initializeCalendar(SimpleDateFormat.java:657)
	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:601)
	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:580)
	at ch.qos.logback.core.util.CachingDateFormatter.<init>(CachingDateFormatter.java:33)
	at ch.qos.logback.classic.layout.TTLLLayout.<init>(TTLLLayout.java:25)
	at ch.qos.logback.classic.BasicConfigurator.configure(BasicConfigurator.java:48)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:164)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
	at org.apache.commons.logging.LogAdapter$Slf4jAdapter.createLocationAwareLog(LogAdapter.java:130)
	at org.apache.commons.logging.LogAdapter.createLog(LogAdapter.java:91)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:67)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:59)
	at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:196)
	at com.jidu.peqcenter.web.WebApplication.main(WebApplication.java:20)
Caused by: java.lang.ClassNotFoundException: org.jacoco.agent.rt.internal_baf4693.core.runtime.ChainNodeHandle
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more
Exception in thread "main" java.lang.NoClassDefFoundError: org/jacoco/agent/rt/internal_baf4693/core/runtime/ChainNodeHandle
	at sun.util.resources.zh.CalendarData_zh.getContents(CalendarData_zh.java)
	at sun.util.resources.OpenListResourceBundle.loadLookup(OpenListResourceBundle.java:137)
	at sun.util.resources.OpenListResourceBundle.loadLookupTablesIfNecessary(OpenListResourceBundle.java:128)
	at sun.util.resources.OpenListResourceBundle.handleKeySet(OpenListResourceBundle.java:96)
	at java.util.ResourceBundle.containsKey(ResourceBundle.java:1824)
	at sun.util.locale.provider.LocaleResources.getCalendarData(LocaleResources.java:129)
	at sun.util.locale.provider.CalendarDataProviderImpl.getFirstDayOfWeek(CalendarDataProviderImpl.java:50)
	at sun.util.locale.provider.CalendarDataUtility$CalendarWeekParameterGetter.getObject(CalendarDataUtility.java:197)
	at sun.util.locale.provider.CalendarDataUtility$CalendarWeekParameterGetter.getObject(CalendarDataUtility.java:182)
	at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObjectImpl(LocaleServiceProviderPool.java:281)
	at sun.util.locale.provider.LocaleServiceProviderPool.getLocalizedObject(LocaleServiceProviderPool.java:265)
	at sun.util.locale.provider.CalendarDataUtility.retrieveFirstDayOfWeek(CalendarDataUtility.java:52)
	at java.util.Calendar.setWeekCountData(Calendar.java:3379)
	at java.util.Calendar.<init>(Calendar.java:1600)
	at java.util.GregorianCalendar.<init>(GregorianCalendar.java:737)
	at java.util.Calendar$Builder.build(Calendar.java:1482)
	at sun.util.locale.provider.CalendarProviderImpl.getInstance(CalendarProviderImpl.java:88)
	at java.util.Calendar.createCalendar(Calendar.java:1666)
	at java.util.Calendar.getInstance(Calendar.java:1655)
	at java.text.SimpleDateFormat.initializeCalendar(SimpleDateFormat.java:657)
	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:601)
	at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:580)
	at ch.qos.logback.core.util.CachingDateFormatter.<init>(CachingDateFormatter.java:33)
	at ch.qos.logback.classic.layout.TTLLLayout.<init>(TTLLLayout.java:25)
	at ch.qos.logback.classic.BasicConfigurator.configure(BasicConfigurator.java:48)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:164)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
	at org.apache.commons.logging.LogAdapter$Slf4jAdapter.createLocationAwareLog(LogAdapter.java:130)
	at org.apache.commons.logging.LogAdapter.createLog(LogAdapter.java:91)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:67)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:59)
	at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:196)
	at com.web.WebApplication.main(WebApplication.java:20)
Caused by: java.lang.ClassNotFoundException: org.jacoco.agent.rt.internal_baf4693.core.runtime.ChainNodeHandle
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more

大佬有联系方式吗~ 有一些细节问题想咨询一下~

**Comment by LeeXinjian** [comment]
跟了一天代码，其实每太看明白。我猜测是不是Trace调用链跟踪的时候，ExtclassLoader加载的类直接跳过就好了。要不插桩的时候，用ExtClassLoad去加载ChainNodeHandle,是肯定加载不到的。

**Comment by alwans** [comment]
要用excludes过滤第三方jar。wx：awanls
